from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'src-tauri' / 'icons' / 'ACE.png'
PUBLIC_LOGO = ROOT / 'public' / 'logo.png'
ICONS_DIR = ROOT / 'src-tauri' / 'icons'

PNG_SIZES = {
    '32x32.png': 32,
    '64x64.png': 64,
    '128x128.png': 128,
    '128x128@2x.png': 256,
    'icon.png': 512,
}

ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]


def resample_filter():
    return getattr(Image, 'Resampling', Image).LANCZOS


def center_square_crop(image: Image.Image) -> Image.Image:
    width, height = image.size
    side = min(width, height)
    left = (width - side) // 2
    top = (height - side) // 2
    right = left + side
    bottom = top + side
    return image.crop((left, top, right, bottom))


def save_png(image: Image.Image, path: Path, size: int) -> None:
    resized = image.resize((size, size), resample_filter())
    resized.save(path, 'PNG', optimize=True)


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f'Missing source icon: {SOURCE}')

    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    PUBLIC_LOGO.parent.mkdir(parents=True, exist_ok=True)

    source = Image.open(SOURCE).convert('RGBA')
    cropped = center_square_crop(source)

    if cropped.size != (1024, 1024):
        cropped = cropped.resize((1024, 1024), resample_filter())

    cropped.save(PUBLIC_LOGO, 'PNG', optimize=True)

    for filename, size in PNG_SIZES.items():
        save_png(cropped, ICONS_DIR / filename, size)

    ico_images = [cropped.resize((size, size), resample_filter()) for size in ICO_SIZES]
    ico_images[-1].save(ICONS_DIR / 'icon.ico', sizes=[(size, size) for size in ICO_SIZES])

    print(f'Source: {SOURCE}')
    print(f'Input size: {source.size}')
    print('Crop: centered square')
    print(f'Output: {PUBLIC_LOGO} {cropped.size}')
    print('Generated PNG and ICO desktop icons.')
    print('Note: icon.icns should be regenerated by Tauri CLI on systems/tools that support ICNS output.')


if __name__ == '__main__':
    main()
